version: '3.4'

volumes:
  nginx_log:

services:
  nginx:
    build:
      context: .
    container_name: logged-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_log:/var/log/nginx
    ports:
      - 80:80
