name: CI

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: waliot/logged-nginx:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_HUB_AUTH_TOKEN }}
